### ISSUE TITLE
Always show song info in status bar

### ISSUE THREAD

**Issue by KingMaraj** [swdotcom/swdc-vscode-musictime#27]
Would it be possible to always show song info in the status bar?
Is there a line of code I can change myself?

**Comment by xavluiz** [comment]
Hi, thank you for the feedback. We would love to show the song in a more interactive way but unfortunately this would mean that the plugin would have to poll the Spotify API.  Due to how many developers we have using the plugin, Spotify starts rate limiting and the whole experience suffers for all users. We've got some ideas for getting around this on particular platforms, but, overall, Spotify is controlling this piece of the experience.  The solution we came to is to show the song information on demand with a click.  We’re always happy for feedback or suggestions. Thank you.
